=== huntabyte/shadcn-svelte/sites/docs/static/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"tailwind": {
			"type": "object",
			"properties": {
				"css": {
					"type": "string"
				},
				"baseColor": {
					"type": "string"
				}
			},
			"required": ["css", "baseColor"]
		},
		"aliases": {
			"type": "object",
			"properties": {
				"utils": {
					"type": "string"
				},
				"components": {
					"type": "string"
				},
				"ui": {
					"type": "string"
				},
				"hooks": {
					"type": "string"
				}
			},
			"required": ["utils", "components"]
		},
		"typescript": {
			"type": "boolean"
		},
		"registry": {
			"type": "string"
		}
	},
	"required": ["tailwind", "aliases"]
}

=== huntabyte/shadcn-svelte/packages/cli/test/fixtures/config-jsconfig/components.json
{
	"tailwind": {
		"config": "tailwind.config.js",
		"css": "src/app.css",
		"baseColor": "zinc"
	},
	"aliases": {
		"components": "$lib/components",
		"utils": "$lib/utils",
		"ui": "$lib/components/ui",
		"hooks": "$lib/hooks"
	},
	"typescript": false,
	"registry": "https://shadcn-svelte.com/registry"
}
